# Generated by Django 2.0.5 on 2019-07-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=150)),
                ('video_id', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('publish', models.DateTimeField()),
                ('love', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'film',
                'ordering': ('-publish',),
            },
        ),
    ]
