# Generated by Django 2.0.5 on 2019-08-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_filmlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=30)),
                ('filmList', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'user_filmlist',
            },
        ),
    ]
