# Generated by Django 2.0.5 on 2019-08-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_user_filmlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_filmlist',
            name='userId',
            field=models.CharField(default='', max_length=30),
        ),
    ]
