# Generated by Django 2.0.5 on 2019-08-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20190816_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_filmlist',
            name='filmList',
            field=models.CharField(default='', max_length=500),
        ),
    ]
