# Generated by Django 2.0.5 on 2019-08-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
    ]
